name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint project
        run: npm run lint

      - name: Lint commit messages
        run: npx --no -- commitlint --from=$(git describe --tags --abbrev=0) --to=HEAD

      - name: Publish project
        run: npm run release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
